// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC9aGbbEqJ11o25NnPVOle1Kx5T5tX0RA',
    appId: '1:830675199832:web:54349a35bf73bcd822672d',
    messagingSenderId: '830675199832',
    projectId: 'she2-5d1cf',
    authDomain: 'she2-5d1cf.firebaseapp.com',
    storageBucket: 'she2-5d1cf.firebasestorage.app',
    measurementId: 'G-G532FHPGHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnocQ67Aey8zUr-yqERPg6PxUAzyZ0TbQ',
    appId: '1:830675199832:android:5618379f62c4863b22672d',
    messagingSenderId: '830675199832',
    projectId: 'she2-5d1cf',
    storageBucket: 'she2-5d1cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtJqOJYD8dOPxlTItVWUvwgT8pSJ4VTuk',
    appId: '1:830675199832:ios:d75c670287652d5c22672d',
    messagingSenderId: '830675199832',
    projectId: 'she2-5d1cf',
    storageBucket: 'she2-5d1cf.firebasestorage.app',
    iosBundleId: 'com.example.sheSecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtJqOJYD8dOPxlTItVWUvwgT8pSJ4VTuk',
    appId: '1:830675199832:ios:d75c670287652d5c22672d',
    messagingSenderId: '830675199832',
    projectId: 'she2-5d1cf',
    storageBucket: 'she2-5d1cf.firebasestorage.app',
    iosBundleId: 'com.example.sheSecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC9aGbbEqJ11o25NnPVOle1Kx5T5tX0RA',
    appId: '1:830675199832:web:da45551c69df016022672d',
    messagingSenderId: '830675199832',
    projectId: 'she2-5d1cf',
    authDomain: 'she2-5d1cf.firebaseapp.com',
    storageBucket: 'she2-5d1cf.firebasestorage.app',
    measurementId: 'G-7KP1DWRN0G',
  );
}
